### ISSUE TITLE
[BUG] apollo read yaml array exception

### ISSUE THREAD

**Issue by weihubeats** [apolloconfig/agollo#316]
apollo read yaml array exception

1. ex:
```yaml
config:
  test:
  - aa
  - bb
  - cc
```

But the value obtained by calling the method `client.GetConfig("test.yaml").GetContent()` is

`config.test=[aa bb cc]`

Maybe it should be `config.test=[aa,bb,cc]` that makes more sense?
